"""empty message

Revision ID: 2c45d608e988
Revises: 835ab7559719
Create Date: 2020-10-09 23:27:53.492570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c45d608e988'
down_revision = '835ab7559719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('Show_venue_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_artist_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'venue')
    op.drop_column('Show', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_artist_fkey', 'Show', 'Artist', ['artist'], ['id'])
    op.create_foreign_key('Show_venue_fkey', 'Show', 'Venue', ['venue'], ['id'])
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
